### ISSUE TITLE
AttributeError: 'str' object has no attribute 'bounding_box'

### ISSUE THREAD

**Issue by kittyifcat** [AuroraWright/owocr#34]
[log.txt](https://github.com/user-attachments/files/23060045/log.txt)

owocr seems to crash immediately or shortly after launching on Windows 11 24H2 after updating owocr to 1.19 or 1.19.1

version 1.18.7 seems to work normally

**Comment by AuroraWright** [comment]
Thanks! Can you try 1.19.2?

**Comment by AuroraWright** [comment]
> > Thanks! Can you try 1.19.2?
> 
> tried updating to it, but seems to result in the same issue
> 
> [log2.txt](https://github.com/user-attachments/files/23061282/log2.txt)

Reproduced it, it should be dealt with now

**Comment by kittyifcat** [comment]
> > > Thanks! Can you try 1.19.2?
> > 
> > 
> > tried updating to it, but seems to result in the same issue
> > [log2.txt](https://github.com/user-attachments/files/23061282/log2.txt)
> 
> Reproduced it, it should be dealt with now

yeah, haven't had issues with it so far

**Comment by AuroraWright** [comment]
Nice, closing then!
